import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Layout from '../components/layout';
import styles from '../styles/Home.module.css';

const App: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    localStorage.getItem('user') ? router.push('/home') : router.push('/login');
  }, [router]);

  return (
    <div className={styles.container}>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
      </Layout>
    </div>
  );
};

export default App;
