import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Layout from '../components/layout';
import Banner from '../components/banner/index';
import TTable from '../components/table/index';

const App: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    localStorage.getItem('user') ? router.push('/') : router.push('/login');
  }, [router]);

  return (
    <Layout>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Banner />
        <h1 className='text-3xl font-bold underline'>Hello World!</h1>
        <TTable />
      </>
    </Layout>
  );
};

export default App;
