import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Birthdays from '../components/birthdays';
import ApplicationBar from '../components/appbar';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ApplicationBar>
        <Birthdays title={'hey hey hey'} />
      </ApplicationBar>
    </div>
  );
};

export default Home;
